//! Build-time bench configuration (`net` feature).
//!
//! `BROKER_HOST` / `BROKER_PORT` are generated by `build.rs` from
//! environment variables set on the build command; they are bench
//! topology and are never committed.  Build the MQTT firmware with:
//!
//! ```sh
//! BROKER_HOST=<ip> BROKER_PORT=8883 cargo build --features net
//! ```
//!
//! See `build.rs` for validation and the deliberate loud-failure
//! behavior when the vars are unset.

#![deny(unsafe_code)]
#![deny(warnings)]

include!(concat!(env!("OUT_DIR"), "/mqtt_endpoint.rs"));
