"""Shared SVG drawing primitives for board pinout diagrams.

Palette constants and small drawing helpers used by every board
template and board module under tools/pinout/.  Nothing here is
Nucleo-144- or Feather-specific-- that lives in the per-form-factor
template modules (e.g. nucleo144.py).
"""

import math

# Palette shared by every board template.  HL/HL_TXT/HIL are the
# generic per-pin highlight mechanism's colors (amber highlight,
# violet HIL taps)-- any per-project overlay can flag its own pins
# with them (the ARS toolhead-sensor project was the first consumer;
# a second board's own highlight rig is another); every other name is
# a generic PCB/pin-role color reused across boards.
HL = '#e8a13d'
HL_TXT = '#8a5a00'
PAD = '#c9c9c9'
SILK = '#03234B'
PCB = '#ffffff'
PCB_EDGE = '#03234B'
INK = '#222222'
MUT = '#555555'
EXT = '#ffffff'
EXT_EDGE = '#888888'
HIL = '#6d28d9'  # distinct from the amber ARS highlights
PWR = '#c0392b'  # power pins (red, the common pinout convention)
GND_FILL = '#111111'  # ground pins (black, white-stroked on strips)


class SvgDoc:
    """Accumulates SVG element strings for one generated drawing."""

    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.out = []

    def emit(self, s):
        self.out.append(s)

    def render(self):
        return '\n'.join(self.out) + '\n'


def open_doc(doc, background='#f7f3eb'):
    """Emit the svg root tag, the generated-artifact marker, and the
    page background.  The marker text names tools/gen_pinout_svg.py
    on purpose-- that thin dispatcher is still the one entry point a
    reader runs to regenerate any board's SVGs, even though the
    drawing logic now lives under tools/pinout/."""
    doc.emit(f'<svg xmlns="http://www.w3.org/2000/svg" '
             f'viewBox="0 0 {doc.width} {doc.height}" '
             f'font-family="Helvetica, Arial, sans-serif">')
    doc.emit('<!-- Generated by tools/gen_pinout_svg.py; edit that '
             'script, not this file. -->')
    doc.emit(f'<rect x="0" y="0" width="{doc.width}" height="{doc.height}" '
             f'fill="{background}"/>')


def ext_box(doc, x, y, w, h, lines, dashed=False):
    """Draw an off-board fixture box (e.g. one stage of an external
    signal chain)."""
    dash = ' stroke-dasharray="6 4"' if dashed else ''
    doc.emit(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="8" '
             f'fill="{EXT}" stroke="{EXT_EDGE}" stroke-width="1.4"{dash}/>')
    ty = y + 20
    for i, ln in enumerate(lines):
        wgt = ' font-weight="bold"' if i == 0 else ''
        sz = 12.5 if i == 0 else 11
        fl = INK if i == 0 else MUT
        doc.emit(f'<text x="{x + w / 2}" y="{ty}" font-size="{sz}" '
                 f'fill="{fl}"{wgt} text-anchor="middle">{ln}</text>')
        ty += 16


def arrow(doc, x1, y1, x2, y2, color='#666666'):
    """Draw a line with an open arrowhead at (x2, y2)."""
    doc.emit(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
             f'stroke="{color}" stroke-width="1.6"/>')
    ang = math.atan2(y2 - y1, x2 - x1)
    for da in (2.6, -2.6):
        hx = x2 + 9 * math.cos(ang + da)
        hy = y2 + 9 * math.sin(ang + da)
        doc.emit(f'<line x1="{x2}" y1="{y2}" x2="{hx}" y2="{hy}" '
                 f'stroke="{color}" stroke-width="1.6"/>')


def hil_tap(doc, x, y, letter):
    """Circled letter marking an analog HIL analyzer tap."""
    doc.emit(f'<circle cx="{x}" cy="{y}" r="9" fill="#ffffff" '
             f'stroke="{HIL}" stroke-width="2"/>')
    doc.emit(f'<text x="{x}" y="{y + 4}" font-size="11" fill="{HIL}" '
             f'font-weight="bold" text-anchor="middle">{letter}</text>')


def hil_dig(doc, x, y, letter):
    """Squared letter marking a digital HIL analyzer tap (an MSO
    digital channel, as opposed to the circular analog taps)."""
    doc.emit(f'<rect x="{x - 8}" y="{y - 8}" width="16" height="16" '
             f'rx="3" fill="#ffffff" stroke="{HIL}" stroke-width="2"/>')
    doc.emit(f'<text x="{x}" y="{y + 4}" font-size="11" fill="{HIL}" '
             f'font-weight="bold" text-anchor="middle">{letter}</text>')
