//! Build-time configuration constants
//!
//! Values are generated by `build.rs` from environment
//! variables and profile-aware defaults.  Override at build
//! time with:
//!
//! ```sh
//! SAMPLE_INTERVAL_SECS=10 cargo build
//! ```
//!
//! See `build.rs` for validation and default logic.

#![deny(unsafe_code)]

include!(concat!(env!("OUT_DIR"), "/sample_interval.rs"));
