[package]
name = "nucleo-h753zi"
version.workspace = true
edition.workspace = true
readme = "README.md"

[[bin]]
bench = false
name = "nucleo-h753zi"
test = false

[dependencies]
cortex-m.workspace = true
critical-section.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
panic-probe.workspace = true

[dependencies.embassy-stm32]
workspace = true
features = ["defmt", "rt", "stm32h753zi", "time-driver-tim3"]

[dependencies.embassy-time]
workspace = true
features = ["defmt", "defmt-timestamp-uptime", "generic-queue-16"]

[dependencies.rtic]
workspace = true
features = ["thumbv7-backend"]

[dependencies.rtic-monotonics]
workspace = true
features = ["defmt", "stm32_tim2", "stm32h753zi"]
