#!/usr/bin/env python3
"""Generate the NUCLEO-N657X0-Q pinout SVGs.

Run from anywhere: `python3 tools/gen_pinout_svg.py`.  The two
checked-in SVGs under docs/src/ are generated artifacts-- edit
this script and regenerate, never the SVGs.

Two variants from one board drawing, per the docs split:
  board -- base board, debug hookup only (board page)
  ars   -- ARS project: debug + peripheral + HIL hookups (pinout.md)

Geometry mirrors the MB1940C top overlay (schematic p.19): Arduino
power+analog headers left (CN5, CN4), digital right (CN14, CN13),
morpho strips outside them (CN3, CN15), ST-LINK and USB-C top,
USER/RESET bottom corners, USB + Ethernet bottom, MCU center.
Header data: UM3417 Rev 3, Table 12.  ARS assignments mirror
docs/src/projects/ars-toolhead-sensor/pinout.md, which is the
authority-- update both together.

House rule: a board drawing always uses the documented board's
real aspect ratio, from its manual-- here 133.34 x 70 mm (UM3417,
Nucleo-144 form factor), so the board rect is 566 x 1080.
"""

import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ARS = '#e8a13d'
ARS_TXT = '#8a5a00'
PAD = '#c9c9c9'
SILK = '#03234B'
PCB = '#ffffff'
PCB_EDGE = '#03234B'
INK = '#222222'
MUT = '#555555'
EXT = '#ffffff'
EXT_EDGE = '#888888'
HIL = '#6d28d9'  # distinct from the amber ARS highlights

# (mark, mcu_pin, func, ars_note)
CN14 = [
    ('D15', 'PH9', 'I2C1_SCL', 'amp SCL'),
    ('D14', 'PC1', 'I2C1_SDA', 'amp SDA'),
    ('AREF', '', 'AVDD', ''),
    ('GND', '', 'Ground', ''),
    ('D13', 'PE15', 'SPI5_SCK', ''),
    ('D12', 'PG1', 'SPI5_MISO', ''),
    ('D11', 'PG2', 'SPI5_MOSI/T14', ''),
    ('D10', 'PA3', 'SPI5_CS/T16', ''),
    ('D9', 'PD7', 'TIM1_CH2', ''),
    ('D8', 'PD12', '--', ''),
]
CN13 = [
    ('D7', 'PE11', '--', ''),
    ('D6', 'PD5', 'TIM1_CH4N', ''),
    ('D5', 'PE10', 'TIM1_CH2N', ''),
    ('D4', 'PE0', '--', ''),
    ('D3', 'PE9', 'TIM1_CH1', 'audio PWM'),
    ('D2', 'PD0', 'GPIO', 'amp mute'),
    ('D1', 'PD8', 'USART3_TX', ''),
    ('D0', 'PD9', 'USART3_RX', ''),
]
CN5 = [
    ('NC', '', '5V_IN test', ''),
    ('IOREF', '', '3V3 ref', ''),
    ('RST', 'NRST', 'Reset', ''),
    ('3V3', '', '3.3V out', ''),
    ('5V', '', '5V out', ''),
    ('GND', '', 'Ground', ''),
    ('GND', '', 'Ground', ''),
    ('VIN', '', 'Power in', ''),
]
CN4 = [
    ('A0', 'PA8', 'ADC12_INP5', 'mic in'),
    ('A1', 'PA9', 'ADC12_INP10', ''),
    ('A2', 'PA10', 'ADC12_INP11', ''),
    ('A3', 'PA12', 'ADC12_INP13', ''),
    ('A4', 'PF3', 'ADC1_INP16', ''),
    ('A5', 'PG15', 'ADC12_INP7', ''),
]

PITCH = 26
BOARD_X, BOARD_W = 310, 566  # 566/1080 ~= 70/133.34 mm (UM3417)
BOARD_R = BOARD_X + BOARD_W
BOARD_CX = BOARD_X + BOARD_W // 2
BOARD_Y, BOARD_H = 70, 1080


def build(variant):
    ars_mode = variant == 'ars'
    W = (BOARD_R + 624) if ars_mode else (BOARD_R + 314)
    H = 1270
    out = []
    emit = out.append

    emit(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
         f'font-family="Helvetica, Arial, sans-serif">')
    emit('<!-- Generated by tools/gen_pinout_svg.py; edit that '
         'script, not this file. -->')
    emit(f'<rect x="0" y="0" width="{W}" height="{H}" fill="#f7f3eb"/>')

    emit(f'<rect x="{BOARD_X}" y="{BOARD_Y}" width="{BOARD_W}" '
         f'height="{BOARD_H}" rx="14" fill="{PCB}" stroke="{PCB_EDGE}" '
         f'stroke-width="3"/>')
    # ST morpho: the populated 2x19 male headers (CN3/CN15) cover
    # only the upper half of two full-length through-hole columns;
    # the lower continuation is the unfitted CN2/CN16 footprint
    # (UM3417 Rev 3, Figure 15, p.31; sect. 8.2).
    morpho_rows = 19
    ars_cn15 = {3, 5, 31, 33, 38}  # PH9/PC1/PE9/PD0/PA1, Table 13
    for x, name, foot in ((318, 'CN3', 'CN2'),
                          (BOARD_R - 28, 'CN15', 'CN16')):
        emit(f'<rect x="{x}" y="200" width="20" '
             f'height="{morpho_rows * 26 + 10}" fill="#161616" rx="3"/>')
        for i in range(morpho_rows):
            cy = 208 + i * 26
            for col, dx in ((0, 3.5), (1, 11)):
                pin_no = 2 * i + 1 + col
                hot = (ars_mode and name == 'CN15'
                       and pin_no in ars_cn15)
                fill = ARS if hot else '#8f8f8f'
                extra = ' stroke="#000" stroke-width="0.5"' if hot else ''
                emit(f'<rect x="{x + dx}" y="{cy}" width="5.5" '
                     f'height="5.5" fill="{fill}"{extra}/>')
                if hot:
                    emit(f'<text x="{x - 4}" y="{cy + 6}" '
                         f'font-size="8.5" fill="{ARS_TXT}" '
                         f'font-weight="bold" text-anchor="end">'
                         f'{pin_no}</text>')
        emit(f'<text x="{x + 10}" y="192" font-size="11" fill="{SILK}" '
             f'text-anchor="middle">{name}</text>')
        foot_y0 = 208 + morpho_rows * 26 + 30
        for i in range(10):
            cy = foot_y0 + i * 26
            for dx in (6, 13.5):
                emit(f'<circle cx="{x + dx}" cy="{cy}" r="2.6" '
                     f'fill="none" stroke="#9a9a9a" stroke-width="1"/>')
        emit(f'<text x="{x + 10}" y="{foot_y0 + 10 * 26 + 6}" '
             f'font-size="8.5" fill="{MUT}" text-anchor="middle">'
             f'{foot}</text>')

    emit(f'<text x="{BOARD_CX}" y="530" font-size="15" fill="{SILK}" '
         f'text-anchor="middle" font-weight="bold">NUCLEO-N657X0-Q</text>')
    emit(f'<text x="{BOARD_CX}" y="548" font-size="11" fill="{SILK}" '
         f'text-anchor="middle">MB1940</text>')

    def header(rows, strip_x, y0, name, side):
        hgt = len(rows) * PITCH + 10
        emit(f'<rect x="{strip_x}" y="{y0 - 5}" width="28" height="{hgt}" '
             f'rx="4" fill="#181818"/>')
        emit(f'<text x="{strip_x + 14}" y="{y0 - 12}" font-size="11" '
             f'fill="{SILK}" text-anchor="middle">{name}</text>')
        for i, (mark, pin, func, note) in enumerate(rows):
            ars = ars_mode and bool(note)
            cy = y0 + i * PITCH + PITCH // 2 - 4
            fill = ARS if ars else PAD
            emit(f'<rect x="{strip_x + 8}" y="{cy - 6}" width="12" '
                 f'height="12" fill="{fill}" stroke="#000" '
                 f'stroke-width="0.6"/>')
            if side == 'left':
                emit(f'<text x="{strip_x + 34}" y="{cy + 4}" font-size="11" '
                     f'fill="{SILK}">{mark}</text>')
                tx, anchor, ta, tb = 296, 'end', BOARD_X, 300
            else:
                emit(f'<text x="{strip_x - 6}" y="{cy + 4}" font-size="11" '
                     f'fill="{SILK}" text-anchor="end">{mark}</text>')
                tx, anchor, ta, tb = BOARD_R + 14, 'start', BOARD_R, BOARD_R + 10
            emit(f'<line x1="{ta}" y1="{cy}" x2="{tb}" y2="{cy}" '
                 f'stroke="#b5b5b0" stroke-width="1"/>')
            core = f'{pin}  {func}' if pin else func
            fillc = ARS_TXT if ars else INK
            weight = ' font-weight="bold"' if ars else ''
            suffix = f'  ({note}) *' if ars else ''
            emit(f'<text x="{tx}" y="{cy + 4}" font-size="12.5" '
                 f'fill="{fillc}"{weight} text-anchor="{anchor}">'
                 f'{core}{suffix}</text>')

    header(CN14, BOARD_R - 72, 220, 'CN14', 'right')
    header(CN13, BOARD_R - 72, 520, 'CN13', 'right')
    header(CN5, 342, 300, 'CN5', 'left')
    header(CN4, 342, 570, 'CN4', 'left')

    # ST-LINK zone + USB-C
    emit(f'<rect x="{BOARD_CX - 30}" y="58" width="60" height="22" rx="6" fill="#3a3a3a"/>')
    emit(f'<rect x="{BOARD_CX - 142}" y="95" width="285" height="90" rx="6" fill="none" '
         f'stroke="{SILK}" stroke-dasharray="5 4" stroke-width="1.2"/>')
    emit(f'<text x="{BOARD_CX + 10}" y="140" font-size="12" fill="{SILK}" '
         f'text-anchor="middle">STLINK-V3EC</text>')
    emit(f'<text x="{BOARD_CX}" y="45" font-size="12.5" fill="{INK}" '
         f'text-anchor="middle">CN10 USB-C: ST-LINK (SWD + RTT), VCP '
         f'console, 5V_STLK power</text>')
    emit('<rect x="344" y="100" width="22" height="70" rx="3" '
         'fill="#161616"/>')
    emit(f'<text x="355" y="185" font-size="9" fill="{SILK}" '
         f'text-anchor="middle">CN1</text>')
    emit(f'<line x1="344" y1="135" x2="300" y2="135" stroke="#b5b5b0"/>')
    emit(f'<text x="296" y="131" font-size="11" fill="{MUT}" '
         f'text-anchor="end">CN1 MIPI20: external</text>')
    emit(f'<text x="296" y="145" font-size="11" fill="{MUT}" '
         f'text-anchor="end">debug probe (SWD/trace)</text>')
    for cy, c in ((110, '#d64545'), (130, '#3fae5a'), (150, '#e0c23e')):
        emit(f'<circle cx="{BOARD_R - 45}" cy="{cy}" r="5" fill="{c}"/>')
    emit(f'<text x="{BOARD_R - 45}" y="172" font-size="9" fill="{SILK}" '
         f'text-anchor="middle">LEDs</text>')

    for x, name in ((430, 'JP1'), (462, 'JP2')):
        emit(f'<rect x="{x}" y="210" width="20" height="44" rx="3" '
             f'fill="#161616"/>')
        emit(f'<rect x="{x + 5}" y="216" width="10" height="14" '
             f'fill="#d9d9d9"/>')
        emit(f'<text x="{x + 10}" y="268" font-size="9" fill="{SILK}" '
             f'text-anchor="middle">{name}</text>')
    emit(f'<text x="446" y="284" font-size="9" fill="{SILK}" '
         f'text-anchor="middle">BOOT0 / BOOT1</text>')
    emit('<rect x="520" y="210" width="56" height="44" rx="3" '
         'fill="#161616"/>')
    emit(f'<text x="548" y="268" font-size="9" fill="{SILK}" '
         f'text-anchor="middle">CN9 PWR SEL</text>')
    emit(f'<text x="296" y="224" font-size="11" fill="{MUT}" '
         f'text-anchor="end">JP2 BOOT1 pos 2 = dev boot</text>')
    emit(f'<text x="296" y="238" font-size="11" fill="{MUT}" '
         f'text-anchor="end">(RAM-boot flow, board page)</text>')

    emit(f'<rect x="{BOARD_CX - 65}" y="580" width="130" height="130" rx="6" '
         'fill="#242424" stroke="#000"/>')
    emit(f'<text x="{BOARD_CX}" y="638" font-size="14" fill="#eee" '
         'text-anchor="middle">STM32</text>')
    emit(f'<text x="{BOARD_CX}" y="656" font-size="14" fill="#eee" '
         'text-anchor="middle">N657X0Q</text>')
    emit(f'<circle cx="{BOARD_CX - 54}" cy="591" r="3" fill="#888"/>')

    emit('<rect x="352" y="760" width="120" height="14" rx="3" '
         'fill="#161616"/>')
    emit(f'<text x="412" y="788" font-size="9" fill="{SILK}" '
         f'text-anchor="middle">CN6 camera</text>')

    emit('<circle cx="372" cy="1078" r="16" fill="#2563eb" stroke="#111"/>')
    emit(f'<text x="372" y="1108" font-size="10" fill="{SILK}" '
         f'text-anchor="middle">B1 USER</text>')
    emit(f'<circle cx="{BOARD_R - 62}" cy="1078" r="16" fill="#1c1c1c" stroke="#666"/>')
    emit(f'<text x="{BOARD_R - 62}" y="1108" font-size="10" fill="{SILK}" '
         f'text-anchor="middle">B2 RESET</text>')
    emit(f'<rect x="{BOARD_CX - 63}" y="1128" width="56" height="22" rx="5" '
         'fill="#3a3a3a"/>')
    emit(f'<text x="{BOARD_CX - 35}" y="1122" font-size="9" fill="{SILK}" '
         f'text-anchor="middle">CN8 USB</text>')
    emit(f'<rect x="{BOARD_CX + 20}" y="1096" width="76" height="54" rx="4" '
         'fill="#3a3a3a"/>')
    emit(f'<rect x="{BOARD_CX + 36}" y="1112" width="44" height="30" fill="#181818"/>')
    emit(f'<text x="{BOARD_CX + 58}" y="1090" font-size="9" fill="{SILK}" '
         f'text-anchor="middle">CN11 ETH</text>')

    emit('<line x1="356" y1="1078" x2="300" y2="1078" stroke="#b5b5b0"/>')
    if ars_mode:
        emit(f'<text x="296" y="1074" font-size="12.5" fill="{ARS_TXT}" '
             f'font-weight="bold" text-anchor="end">PC13  EXTI13  '
             f'(user button) *</text>')
        emit(f'<text x="296" y="1090" font-size="11" fill="{MUT}" '
             f'text-anchor="end">spare EXTI, no wiring</text>')
    else:
        emit(f'<text x="296" y="1074" font-size="12.5" fill="{INK}" '
             f'text-anchor="end">PC13  EXTI13</text>')
    emit(f'<line x1="{BOARD_CX + 96}" y1="1123" x2="{BOARD_R + 10}" y2="1123" stroke="#b5b5b0"/>')
    emit(f'<text x="{BOARD_R + 14}" y="1119" font-size="12.5" fill="{INK}">on-chip '
         f'ETH1 RMII, LAN8742A PHY</text>')
    emit(f'<text x="{BOARD_R + 14}" y="1135" font-size="11" fill="{MUT}">net feature: '
         f'DHCP + SNTP + MQTT/TLS</text>')

    if not ars_mode:
        emit(f'<line x1="{BOARD_R - 6}" y1="700" x2="{BOARD_R + 10}" y2="770" '
             f'stroke="#b5b5b0"/>')
        emit(f'<text x="{BOARD_R + 14}" y="766" font-size="11" fill="{MUT}">ST morpho '
             f'CN3/CN15: most remaining I/O</text>')
        emit(f'<text x="{BOARD_R + 14}" y="780" font-size="11" fill="{MUT}">(UM3417 '
             f'Tables 13-14)</text>')
        emit(f'<text x="310" y="1200" font-size="12.5" fill="{INK}">Debug '
             f'hookup: CN10 USB-C alone carries SWD, RTT, and the VCP; '
             f'CN1 takes an external probe.</text>')
        emit(f'<text x="310" y="1222" font-size="11" fill="{MUT}">Arduino '
             f'V3 header data: UM3417 Rev 3, Table 12.  A0-A5 route '
             f'through the on-board 3.3V-to-1.8V</text>')
        emit(f'<text x="310" y="1237" font-size="11" fill="{MUT}">'
             f'adaptation amplifier; the 1.8V-domain ADC pin is shown.  '
             f'ARS assignments: see the project pinout.</text>')
        emit('</svg>')
        return W, out

    # ── ARS variant: morpho routing, external chain, HIL taps ──
    emit(f'<line x1="{BOARD_R - 6}" y1="700" x2="{BOARD_R + 10}" y2="800" stroke="#b5b5b0"/>')
    emit(f'<text x="{BOARD_R + 14}" y="796" font-size="11" fill="{MUT}">morpho CN15 '
         f'is the routing of record for the amp:</text>')
    emit(f'<text x="{BOARD_R + 14}" y="810" font-size="11" fill="{MUT}">pin 3 PH9 SCL, '
         f'pin 5 PC1 SDA, pin 31 PE9, pin 33 PD0;</text>')
    emit(f'<text x="{BOARD_R + 14}" y="824" font-size="11" fill="{MUT}">pin 38 PA1 = '
         f'G2 fallback ADC tap</text>')

    def ext_box(x, y, w, h, lines, dashed=False):
        dash = ' stroke-dasharray="6 4"' if dashed else ''
        emit(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="8" '
             f'fill="{EXT}" stroke="{EXT_EDGE}" stroke-width="1.4"{dash}/>')
        ty = y + 20
        for i, ln in enumerate(lines):
            wgt = ' font-weight="bold"' if i == 0 else ''
            sz = 12.5 if i == 0 else 11
            fl = INK if i == 0 else MUT
            emit(f'<text x="{x + w / 2}" y="{ty}" font-size="{sz}" '
                 f'fill="{fl}"{wgt} text-anchor="middle">{ln}</text>')
            ty += 16

    def arrow(x1, y1, x2, y2, color='#666666'):
        emit(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
             f'stroke="{color}" stroke-width="1.6"/>')
        import math
        ang = math.atan2(y2 - y1, x2 - x1)
        for da in (2.6, -2.6):
            hx = x2 + 9 * math.cos(ang + da)
            hy = y2 + 9 * math.sin(ang + da)
            emit(f'<line x1="{x2}" y1="{y2}" x2="{hx}" y2="{hy}" '
                 f'stroke="{color}" stroke-width="1.6"/>')

    def hil_tap(x, y, letter):
        emit(f'<circle cx="{x}" cy="{y}" r="9" fill="#ffffff" '
             f'stroke="{HIL}" stroke-width="2"/>')
        emit(f'<text x="{x}" y="{y + 4}" font-size="11" fill="{HIL}" '
             f'font-weight="bold" text-anchor="middle">{letter}</text>')

    # External audio chain, right column, aligned to the D3 row
    d3_y = 520 + 4 * PITCH + PITCH // 2 - 4
    x0 = BOARD_R + 314
    ext_box(x0, 600, 250, 60,
            ['RC low-pass', 'passive, values at gate G3'])
    ext_box(x0, 700, 250, 92,
            ['MAX9744 class-D amp', 'LEFTIN = JP2.2, SDA = JP2.4',
             'MUTE_INV = JP2.8 (low = mute)', 'VDDIO = Nucleo 3V3, I2C 0x4B'])
    ext_box(x0, 832, 250, 60,
            ['EX25VT2-4 exciter', 'clamped to the H2C toolhead'])
    ext_box(x0, 932, 250, 76,
            ['external PVDD supply', '4.5-14 V, never the Nucleo',
             'grounds commoned'], dashed=True)
    # Mic feeds A0, so it lives on the left, under the CN4 labels
    ext_box(40, 740, 250, 76,
            ['MEMS mic breakout', 'SPH8878LR5H-1 (modified)',
             'VCC = 3V3, AUD = analog out'])

    # D3 (PE9) -> RC -> amp -> exciter; PVDD up into the amp
    arrow(BOARD_R + 202, d3_y, x0, 626)
    arrow(x0 + 125, 660, x0 + 125, 700)
    arrow(x0 + 125, 792, x0 + 125, 832)
    # PVDD feeds the amp; route up the clear lane left of the chain
    emit(f'<line x1="{x0 + 10}" y1="945" x2="{x0 - 15}" y2="945" stroke="#666666" '
         'stroke-width="1.6"/>')
    emit(f'<line x1="{x0 - 15}" y1="945" x2="{x0 - 15}" y2="772" stroke="#666666" '
         'stroke-width="1.6"/>')
    arrow(x0 - 15, 772, x0, 772)
    # I2C + mute leave on the morpho strip, straight into the amp
    arrow(BOARD_R - 4, 746, x0, 746)
    emit(f'<text x="{(BOARD_R + x0) // 2}" y="738" font-size="10.5" fill="{MUT}" '
         f'text-anchor="middle">I2C1 + MUTE_N (morpho CN15 pins '
         f'3/5/33)</text>')
    # Mic AUD up the clear left margin into the A0 row; heads only
    # on the final segment, matching the PVDD lane
    a0_y = 570 + PITCH // 2 - 4
    emit('<line x1="165" y1="740" x2="80" y2="740" stroke="#666666" '
         'stroke-width="1.6"/>')
    emit(f'<line x1="80" y1="740" x2="80" y2="{a0_y}" stroke="#666666" '
         f'stroke-width="1.6"/>')
    arrow(80, a0_y, 108, a0_y)
    emit(f'<text x="72" y="660" font-size="10.5" fill="{MUT}" '
         f'text-anchor="middle" transform="rotate(-90 72 660)">AUD '
         f'(analog)</text>')

    # HIL taps (hil-measurements.md, gate G3).  Circled letters
    # only; the legend decodes them.  Floating per-tap labels
    # crowded the chain and read as part of it.
    hil_tap(x0 - 54, d3_y - 6, 'A')
    hil_tap(x0 + 125, 680, 'B')
    hil_tap(BOARD_R + 170, 746, 'C')

    # Legend
    emit(f'<rect x="310" y="1190" width="12" height="12" fill="{ARS}" '
         f'stroke="#000" stroke-width="0.6"/>')
    emit(f'<text x="330" y="1200" font-size="12.5" fill="{INK}">* '
         f'ARS-assigned signal (provisional, gates G0-G5) -- pinout.md '
         f'is the authority</text>')
    emit(f'<text x="310" y="1222" font-size="12.5" fill="{INK}">HIL '
         f'analyzer taps, gate G3 (hil-measurements.md):</text>')
    for lx, letter, desc in (
        (640, 'A', 'PWM carrier, pre-RC'),
        (860, 'B', 'filtered line, post-RC'),
        (1090, 'C', 'I2C decode, SCL/SDA'),
    ):
        emit(f'<circle cx="{lx}" cy="1218" r="9" fill="#ffffff" '
             f'stroke="{HIL}" stroke-width="2"/>')
        emit(f'<text x="{lx}" y="1222" font-size="11" fill="{HIL}" '
             f'font-weight="bold" text-anchor="middle">{letter}</text>')
        emit(f'<text x="{lx + 16}" y="1222" font-size="12.5" '
             f'fill="{INK}">{desc}</text>')
    emit(f'<text x="310" y="1244" font-size="11" fill="{MUT}">Arduino V3 '
         f'header data: UM3417 Rev 3, Table 12.  A0-A5 route through the '
         f'on-board 3.3V-to-1.8V adaptation amplifier; the 1.8V-domain '
         f'ADC pin is shown.</text>')
    emit('</svg>')
    return W, out


for variant, path in (
    ('board', os.path.join(REPO, 'docs/src/boards/'
                                 'nucleo-n657x0-pinout.svg')),
    ('ars', os.path.join(REPO, 'docs/src/projects/ars-toolhead-sensor/'
                               'nucleo-n657x0-ars-pinout.svg')),
):
    w, svg = build(variant)
    with open(path, 'w') as f:
        f.write('\n'.join(svg) + '\n')
    print('wrote', path, f'({w}px wide, {len(svg)} elements)')
